### ISSUE TITLE
help: how do I make "mail to:" function?

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#14]
I realized that I had written: write to info@woundstudycenter.org but it should be .com, but when I changed it, the email wasn't highlighted anymore. Can you make all emails "mail to:" so when you click them it opens an email?

**Comment by orzubalsky** [comment]
You'd have to write it into the links that you're creating in the admin. All you have to do is to add "mailto:" before the email address. For example: mailto:info@woundstudycenter.com.

I updated the one in the intro for the site but maybe there are more on the website you'd want to update.
