### ISSUE TITLE
help: how do I connect info@woundstudycenter.com to woundstudycenter@gmail.com

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#15]
I want to be able to send messages from the study center gmail (woundstudycenter@gmail.com) from info@woundstudycenter.com, but I don't know how. Can you help me? The login to woundstudycenter@gmail.com is 41coopergallery

I would love to do the same with caroline@woundstudycenter.com (link to carolinewoolard@gmail.com) <--- let me know what to do to make this happen...

**Comment by orzubalsky** [comment]
I set it up through your gmail & gandi!
