### ISSUE TITLE
feature: add FAQ at the top

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#31]
I need a section (it can be physically located last, at the bottom of the page) where I answer questions and thank NYFA and Eyebeam, and perhaps name you, me, Len, etc. and talk about where this resource comes from, also say something about the show at cooper (can we link to the old website??? or show images from the exhibition at least???).

![screen shot 2017-09-01 at 11 12 09 am](https://user-images.githubusercontent.com/925548/29976008-8ff947f6-8f06-11e7-8f66-0be66d7bd699.png)

**Comment by orzubalsky** [comment]
I added it in the admin backend, you can edit it at http://studycollaboration.orzubalsky.com/admin/base/contentblock/8/change/
