### ISSUE TITLE
bug: I don't know how to add a Training (the backend doesn't match the frontend)

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#32]
![screen shot 2017-09-01 at 11 20 24 am](https://user-images.githubusercontent.com/925548/29976316-a2e75b54-8f07-11e7-9acf-65a89fd2ba2a.png)

**Comment by orzubalsky** [comment]
The screencap above is of the `content block` admin page, you want to look for the `trainings` one. It's at http://studycollaboration.orzubalsky.com/admin/base/training/add/.
