### ISSUE TITLE
bug: I dont see facilitators that I just added

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#36]
I just added Emilio, and Susan has been there for a while, but I don't see them when I try to associate them with a training... why?

![screen shot 2017-09-01 at 2 46 39 pm](https://user-images.githubusercontent.com/925548/29983556-7f7e69b0-8f24-11e7-8ccc-afb435575959.png)

**Comment by orzubalsky** [comment]
There was a mixup between the old `facilitator` model and the new `contributor` model that we've moved to. It's fixed now but you should reselect contributors for this one training: http://studycollaboration.orzubalsky.com/admin/base/training/19/change/
