### ISSUE TITLE
pixel polish: please add the Rubin Foundation logo to the bottom of the site

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#4]
![screen shot 2016-09-29 at 8 38 50 pm](https://cloud.githubusercontent.com/assets/925548/18977051/2ae1ba0e-8685-11e6-8cf2-0b5f6082aa1a.png)

They gave $20k and are paying us...

![r-foundation_sign082906 1](https://cloud.githubusercontent.com/assets/925548/18977017/e5550536-8684-11e6-9a2e-d647e1144fb2.jpg)

**Comment by orzubalsky** [comment]
I linked the logo in the about content block, let me know if you want to style it differently.
