### ISSUE TITLE
bug: can the sign up email form be on a new page?

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#44]
maybe you are still working on this? looks broken (can it be on a new page)?

![screen shot 2017-09-02 at 5 35 54 pm](https://user-images.githubusercontent.com/925548/29998938-46f345ac-9005-11e7-888f-7bd0ca3ec500.png)

**Comment by orzubalsky** [comment]
Yeah it was leftover from previous work, it's no longer there :)
