### ISSUE TITLE
bug: when there's no image, don't leave a big blank between the description and the PDF and bio

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#45]
People will miss the PDF when they click on a METHOD to learn more, as it's below the fold!

![screen shot 2017-09-04 at 9 58 04 am](https://user-images.githubusercontent.com/925548/30029549-aa30b03e-9157-11e7-94e4-f899814c45d9.png)

**Comment by orzubalsky** [comment]
Interesting, this happened because there was some html in the content that was pasted in the practice description form. I fixed it there and also made a general change to the style of the website so it doesn't happen again.
