### ISSUE TITLE
bug: image wont upload for a tool

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/wou#9]
For some reason, the images I'm trying to upload aren't working. Are there specifications that I should know about, to enable uploads?

![screen shot 2016-10-01 at 9 41 21 am](https://cloud.githubusercontent.com/assets/925548/19014466/47e4efae-87bb-11e6-9382-27e641172bcf.png)

**Comment by orzubalsky** [comment]
Oops, when I updated the code last time I changed the upload settings in the code- it should be back to normal now.
